## `Numpy (Numerical Python)`
- Numerical Python

- used for working with arrays.
- List serves the purpose of the arrays in python, but are significantly slow.
- Stored at one continous place in memory unlike lists. That's why numpy is faster to process, efficient to access, and manipulate.
- partially written in python but the part which require fast computation are written in C or C++.

- Array object in Numpy is `ndarray`. 

- The array-like objects in python like list and tuple can be converted into numpy array.

#### &emsp; `Package installation`
```python
    # Type
    pip install numpy
    # in command prompt after activating the environment.
```

In [22]:
# check numpy version
import numpy as np
print(np.__version__)

1.23.5


In [23]:
# Create ndarray object using array() function
arr = [1, 2, 3, 4]
np_arr = np.array(arr)
print(type(np_arr), np_arr)

<class 'numpy.ndarray'> [1 2 3 4]


#### `Determine shape of array with 'shape' attribute`

In [24]:
arr = np.array([1, 2, 3, 4])
print(arr.shape)

(4,)


In [25]:
arr = np.array(
    [[1, 2, 3], [3, 4, 5]]
)
print(arr.shape)

(2, 3)


#### `What does shape tuple represents?`
- Integers at every index represents the number of elements present in its corresponding dimension.

#### `Dimensions in Numpy Array`

#### &emsp;`0-D Arrays`
- The arrays are scalers with no shape.

In [1]:
import numpy as np
arr = np.array(10)

print(arr)
print(type(arr))
print(arr.shape)

10
<class 'numpy.ndarray'>
()


#### &emsp;`1-D Arrays`
- The arrays consists 0-D arrays as its elements.

In [2]:
import numpy as np
arr = np.array([11, 12, 13, 14, 15])

print(arr)
print(type(arr))
print(arr.shape)

[11 12 13 14 15]
<class 'numpy.ndarray'>
(5,)


#### &emsp;`2-D Arrays`
- The arrays consists 1-D arrays as its elements.
- Represents matrix

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
# print(type(arr))
# print(arr.shape)

[[1 2 3]
 [4 5 6]]


#### &emsp;`3-D Arrays`
- The arrays consists 2-D arrays as its elements.

In [4]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(type(arr))
print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(2, 2, 3)


#### &emsp;Determine number of dimensions of `ndarray` object.

In [5]:
import numpy as np

arr_1 = np.array(42)
arr_2 = np.array([1, 2, 3, 4, 5])
arr_3 = np.array([[1, 2, 3], [4, 5, 6]])
arr_4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print('Num of dim in arr_1: ', arr_1.ndim)
print('Num of dim in arr_2: ', arr_2.ndim)
print('Num of dim in arr_3: ', arr_3.ndim)
print('Num of dim in arr_4: ', arr_4.ndim)

Num of dim in arr_1:  0
Num of dim in arr_2:  1
Num of dim in arr_3:  2
Num of dim in arr_4:  3


#### &emsp;Higher Dimension in Arrays
- When creating numpy array using `array()`, it is possible to create array of any dimension with the use of `ndmin` argument.

In [6]:
import numpy as np

arr = np.array([21, 22, 23, 24], ndmin=6)

print(arr)
print('Num of dim in arr: ', arr.ndim)

[[[[[[21 22 23 24]]]]]]
Num of dim in arr:  6


## `Numpy Array Indexing`
- Access elements in array using index number.
- Index starts from 0.

#### &emsp;`Accessing 1-D Array`

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])

1
2


#### &emsp;`Accessing 2-D Array`

In [8]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0, 1])

2


#### &emsp;`Accessing 3-D Array`

In [9]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 1])

5


#### &emsp;`Negative Indexing`

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[-1])

4


#### &emsp;`Array Slicing`
- &emsp;&emsp;array_name[_start-index_:_end-index_]<br/>
- &emsp;&emsp;array_name[_start-index_:_end-index_:_step_]

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
import numpy as np
print(arr[1:5])
print(arr[1:])
print(arr[:3])

[2 3 4 5]
[2 3 4 5 6 7 8 9]
[1 2 3]


#### &emsp;`Negative Indexing`

In [13]:
import numpy as np
print(arr[-4:-3])
print(arr[-2:])
print(arr[:-5])

[6]
[8 9]
[1 2 3 4]


#### &emsp;`Step`

In [ ]:
print(arr[0:6:1])
print(arr[0:6:2])
print(arr[::2])

In [ ]:
print(arr[-4::2])
print(arr[::-1])

#### &emsp;`Slicing 2-D Array`

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[0:6:1])
print(arr[0:6:2])
print(arr[0:6:3])

[1 2 3 4 5 6]
[1 3 5]
[1 4]


In [14]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [15]:
import numpy as np
print(arr[0, 1:6])
print(arr[0:2, 0])

[2 3 4 5 6]
[1 7]


In [16]:
import numpy as np
print(arr[:, 0])

[1 7]


In [5]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12],
                [3,4,5,6,10,15]])
print(arr[::2,0])

[1 3]


#### &emsp; `Data Types in Numpy`
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- M - datetime
- S - string

#### &emsp;`Check data type`

In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [19]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])   #cant change to integer like we changed int to float cuz string cant be changed to int 
print(arr.dtype)

<U6


In [21]:
import numpy as np
int('3')

3

In [22]:
import numpy as np
arr = np.array([1, '2', '3'], dtype='i')    #1 2 and 3 are in string here but when we conver to string it is possible cuz 0-9 is numeric val
print(arr.dtype)

int32


In [20]:
import numpy as np
arr = np.array([1, 'banana', 'cherry'], dtype='i')
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'banana'

#### &emsp;`Converting Data Type of Existing Array`

In [23]:
import numpy as np
arr = np.array([5.8, 6.4, 7.3])
new_arr = arr.astype('i')
print(new_arr)
print(new_arr.dtype)

[5 6 7]
int32


In [24]:
import numpy as np
arr = np.array([5, 6, 7])
new_arr = arr.astype('f')
print(new_arr)
print(new_arr.dtype)

[5. 6. 7.]
float32


#### `Copy and View`
- Main Difference: `copy()` creates array in new object location while `view()` provides reference to original array. 
- changes in original array aren't seen in new array created with `copy()` and vice-versa but seen in array created with `view()`.

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

x = arr.copy()    #copy le garda ele update bhayo index 0 ma 1 ko satto 42 
arr[0] = 42

print(arr)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]
[1 2 3 4 5]


In [26]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()    #change garisakeko le changed val nai e=dekahucha 
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()    
arr[0] = 42

print(arr)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


#### `Reshape`
- arrange the elements in different dimensions.
- total number of elements should be equal to product of all dimensions.

In [27]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
# 1d-2d 
import numpy as np
arr2 = arr.reshape(3, 4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
# 1d-3d
import numpy as np
arr3 = arr.reshape(2, 2, 3)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [30]:
import numpy as np
arr0 = arr3.reshape(-1)
print(arr0)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
import numpy as np
arr3 = arr.reshape(2, 2, -1)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [33]:
import numpy as np
print(arr3.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### `Iterating over Arrays`
- going through the each of the elements one at a time

In [11]:
import numpy as np
# Iterating on 1-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8 , 9, 10, 11, 12])

for ele in arr:
    print(f"element is: {ele}\n")

element is: 1

element is: 2

element is: 3

element is: 4

element is: 5

element is: 6

element is: 7

element is: 8

element is: 9

element is: 10

element is: 11

element is: 12



In [35]:
# Iterating on 2-D array
import numpy as np
arr = arr.reshape(3, 4)
print(arr)

for ele in arr:
    print(f"\nelement is: {ele}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

element is: [1 2 3 4]

element is: [5 6 7 8]

element is: [ 9 10 11 12]


In [16]:
# Iterating on 2-D array
import numpy as np
arr = arr.reshape(3, 4)

for ele in arr:
    for x in ele:
        print(f"\nelement is: {x}")


element is: 1

element is: 2

element is: 3

element is: 4

element is: 5

element is: 6

element is: 7

element is: 8

element is: 9

element is: 10

element is: 11

element is: 12


In [36]:
# Iterating on 3-D array
import numpy as np

arr = arr.reshape(2, 2, 3)
print(arr)

for ele in arr:
    print(f"\nelement is: {ele}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

element is: [[1 2 3]
 [4 5 6]]

element is: [[ 7  8  9]
 [10 11 12]]


In [37]:
# Iterating down to scalers for array having
# dimension greater than 1
arr = arr.reshape(3, 4)
import numpy as np

# vanilla method
for row in arr:
    for j in row:
        print(f'element {j}')

element 1
element 2
element 3
element 4
element 5
element 6
element 7
element 8
element 9
element 10
element 11
element 12


In [38]:
# Iterating using nditer()
import numpy as np

for x in np.nditer(arr):
    print(f'nditer  element {x}')

nditer  element 1
nditer  element 2
nditer  element 3
nditer  element 4
nditer  element 5
nditer  element 6
nditer  element 7
nditer  element 8
nditer  element 9
nditer  element 10
nditer  element 11
nditer  element 12


In [39]:
import numpy as np
step = 2
print(arr[:, ::step])

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [40]:
# Iterating with different step size
import numpy as np
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7
9
11


In [41]:
# Iterating with np.ndenumerate()
import numpy as np
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12


#### `Joining Arrays` 

In [42]:
# Joining with concatinate() for 1-D
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [44]:
# Joining with concatinate() for 2-D
# axis -> 0 is along 1st dimension
# axis -> 1 is along 2nd dimension
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [20]:
# Joining with stack()
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [1]:
# Joining with stack()
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# axis=-1 for last dimension
arr = np.stack((arr1, arr2), axis=-1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [2]:
# Joining with stack()
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.stack((arr1, arr2), axis=0)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
# Joining with stack()
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6], [13, 14, 15]])
arr2 = np.array([[7, 8, 9], [10, 11, 12], [16, 17, 18]])

arr = np.stack((arr1, arr2), axis=2)
arr

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]],

       [[13, 16],
        [14, 17],
        [15, 18]]])

In [4]:
# Joining with stack()
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# axis=-1 for last dimension
arr = np.stack((arr1, arr2), axis=-1)
arr

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

#### `Stacking with helper functions 'hstack()' 'vstack()' 'dstack()`

In [5]:
# Stacking along rows
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.hstack((arr1, arr2))
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [24]:
# Stacking along columns
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.vstack((arr1, arr2))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
# Stacking along depth
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.dstack((arr1, arr2))
arr

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

#### `Splitting with array_split()`
- returns list containing arrays

In [27]:
# Splitteing 1-D arrays
num_of_splits = 2
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_arr = np.array_split(arr, num_of_splits)
new_arr

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [6]:
# Splitteing 2-D arrays
import numpy as np
num_of_splits = 5           #5 lekhda auta empty arr aucha cuz max arr 4 ho 
arr = np.array([[1, 2], 
                [3, 4], 
                [5, 6], 
                [7, 8]])
new_arr = np.array_split(arr, num_of_splits)
new_arr

[array([[1, 2]]),
 array([[3, 4]]),
 array([[5, 6]]),
 array([[7, 8]]),
 array([], shape=(0, 2), dtype=int32)]

#### `Splitting with hsplit(), vsplit(), dsplit()`
- returns list containing arrays

In [10]:
# Splitteing 2-D arrays
num_of_splits = 2
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
new_arr = np.vsplit(arr, num_of_splits)
new_arr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [14]:
# Splitteing 2-D arrays
num_of_splits = 2
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
new_arr = np.hsplit(arr, num_of_splits)
new_arr

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [9]:
# dsplit() works for array with dimension equal or greater than 3.
num_of_splits = 2
arr = np.array([[[1, 2],
                 [3, 4]], 
                [[5, 6],
                 [7, 8]]])
new_arr = np.dsplit(arr, num_of_splits)
new_arr

[array([[[1],
         [3]],
 
        [[5],
         [7]]]),
 array([[[2],
         [4]],
 
        [[6],
         [8]]])]

#### `Search elements in array` 

In [16]:
# in 1-D Array
arr = np.array([1, 2, 3, 4, 5, 3, 3])
#print (arr==3)                  #true false ma output dincha 3 hako index ma true res dincha and nabhakoma false
x = np.where(arr == 3)          #kun index ma 3 cha tyo index print huncha 


print(x)

(array([2, 5, 6], dtype=int64),)


In [11]:
# in 2-D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
x = np.where(arr == 3)          #

print(x)

(array([1], dtype=int64), array([0], dtype=int64))


In [12]:
# in 2-D array
arr = np.array([[1, 2], [3, 4], [3, 6], [7, 8]])
x = np.where(arr == [3, 4])

print(x)

(array([1, 1, 2], dtype=int64), array([0, 1, 0], dtype=int64))


In [13]:
# find even elements in array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


#### `Sorting numpy arrays with sort()`
- returns copy of original array leaving original array unchanged.

In [14]:
# sorting 1-D array
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [15]:
# sorting boolean array
arr = np.array([True, False, True])    #false lai 0 mancha ra true lai 1 mancha similarly alphabetically pani f ra t hereko 
print(np.sort(arr))

[False  True  True]


In [16]:
# Sorting string array
arr = np.array(['Python', 'Java', 'Js', 'Mojo'])
print(np.sort(arr))

['Java' 'Js' 'Mojo' 'Python']


In [17]:
# sorting string array
arr = np.array(['Python', 'Java', 'JS', 'Mojo'])    #capital letter lai badi priority deko le JS first ma ako 
print(np.sort(arr)) 

['JS' 'Java' 'Mojo' 'Python']


In [18]:
arr = np.array([[3, 2, 4], [5, 0, 1]])  #array testo ko testai huncha bhitra ko ele matra sort huncha 
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


#### `Filtering numpy arrays`
- excluding or including elements from existing array based on some condition.
- index with boolean value `True` is included
- index with boolean value `False` is excluded

In [19]:
# hardcoded index
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
new_arr = arr[x]
new_arr

array([41, 43])

In [20]:
# conditional filer with for loop
arr = np.array([41, 42, 43, 44])
new_arr = []
for ele in arr:
    if ele > 42:
        new_arr.append(ele)
print(new_arr)

[43, 44]


In [21]:
# conditional filter
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
new_arr = arr[filter_arr]
new_arr

array([43, 44])

In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.square(arr))

[ 1  4  9 16]
